---
name: Publish tree-sitter parsers

on:
  push:
    branches:
      - 'main'
    paths:
      - tree-sitter-parsers.json
      - .github/workflows/publish-ts-parsers.yml
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      parsers: ${{ steps.set-matrix.outputs.parsers }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "MATRIX=$(cat ./tree-sitter-parsers.json | tr -d '\n\r')" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      max-parallel: 10 # Don't DDOS the luarocks servers
      matrix: ${{ fromJson(needs.generate-matrix.outputs.parsers) }}
    steps:
      - name: Checkout parser repository
        run: |
          git clone ${{ matrix.parsers.url }}
          ls
