---
name: Publish tree-sitter parsers

on:
  push:
    branches:
      - 'main'
    paths:
      - tree-sitter-parsers.json
      - .github/workflows/publish-ts-parsers.yml
  workflow_dispatch:

  # TODO: Remove
concurrency:
  group: publish-tree-sitter-parsers
  cancel-in-progress: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          echo "MATRIX=$(cat ./tree-sitter-parsers.json | tr -d '\n\r')" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      max-parallel: 10 # Don't DDOS the luarocks servers
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Clone parser repository
        run: |
          REPO_URL=$(echo "${{ matrix.parsers.install_info.url }}" | sed 's/\.git$//')
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          git clone --filter=blob:none "$REPO_URL.git" .

      - name: Get latest Tag and parser name
        id: get-release
        run: |
          echo "PARSER_NAME=tree-sitter-${{ matrix.parsers.lang }}" >> $GITHUB_ENV
          # Check for semver tags
          TAGS="$(git for-each-ref --sort=authordate --format '%(refname)' refs/tags )"
          if [[ -n "$TAGS" ]]; then
            echo "Found tags:"
            echo "$TAGS"
          fi
          TAG="$(git for-each-ref --sort=authordate --format '%(refname)' refs/tags | sed 's/refs\/tags\/\(.*\)/\1/' | grep -P '^[v]*[0-9]{1,}.[0-9]{1,}.[0-9]{1,}' | tail -n1)"
          if [[ -z "$TAG" ]]; then
            # Try without patch
            TAG="$(git for-each-ref --sort=authordate --format '%(refname)' refs/tags | sed 's/refs\/tags\/\(.*\)/\1/' | grep -P '^[v]*[0-9]{1,}.[0-9]{1,}' | tail -n1)"
          fi
          if [[ -z "$TAG" ]]; then
            # Try without minor
            TAG="$(git for-each-ref --sort=authordate --format '%(refname)' refs/tags | sed 's/refs\/tags\/\(.*\)/\1/' | grep -P '^[v]*[0-9]{1,}' | tail -n1)"
          fi
          if [[ -n "$TAG" ]]; then
            echo "Found $TAG"
            git checkout $TAG
            echo "TAG=$TAG" >> $GITHUB_ENV
            VERSION=$(echo "$TAG" | sed 's/v\(.*\)/\1/')
            echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
            echo "GITHUB_REF_TYPE_OVERRIDE=tag" >> $GITHUB_ENV
            echo "GITHUB_REF_NAME_OVERRIDE=$TAG" >> $GITHUB_ENV
            echo "GITHUB_REPOSITORY_OVERRIDE=$(echo '${{ env.REPO_URL }}' | awk -F/ '{print $4"/"$5}')" >> $GITHUB_ENV
          else
            echo "PUBLISHED_COUNT=NOTHING" >> $GITHUB_ENV
          fi

      - name: Install Lua
        if: ${{ env.RELEASE_VERSION != '' }}
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"

      - name: Install tree-sitter parser
        uses: baptiste0928/cargo-install@v3
        if: ${{ matrix.parsers.install_info.requires_generate_from_grammar == 'true' }}
        with:
          crate: tree-sitter

      - uses: actions/setup-node@v4
        if: ${{ matrix.parsers.install_info.requires_generate_from_grammar == 'true' || matrix.parsers.install_info.generate_requires_npm == 'true' }}

      - name: Install Luarocks
        if: ${{ env.RELEASE_VERSION != '' }}
        uses: hishamhm/gh-actions-luarocks@master

      - if: ${{ env.RELEASE_VERSION != '' }}
        run: |
          echo "PUBLISHED_COUNT=$(luarocks --only-server=https://luarocks.org/manifests/neorocks search ${{ env.PARSER_NAME }} ${{ env.RELEASE_VERSION }} --porcelain | wc -l)" >> $GITHUB_ENV

      - name: Get Rockspec template
        if: ${{ env.RELEASE_VERSION != '' }}
        uses: actions/checkout@v4
        with: 
          sparse-checkout: |
            resources
          path: rockspec-template

      - name: Prepare Rockspec template
        if: ${{ env.PUBLISHED_COUNT == '0' }}
        env:
          SOURCES_JSON: ${{ toJson(matrix.parsers.install_info.files) }}
        run: |
          mv rockspec-template/resources/tree-sitter-parser-rockspec.template rockspec.template
          sed -i 's/LANG/${{ matrix.parsers.lang }}/g' rockspec.template
          echo "REQUIRES_GENERATE: ${{ matrix.parsers.install_info.requires_generate_from_grammar }}"
          # Conver sources to lua
          SOURCES_TBL=$(echo "$SOURCES_JSON" | jq -r '"{ " + (map("\"" + . + "\"") | join(", ")) + " }"')
          sed -i 's@SOURCES@'"$SOURCES_TBL"'@' rockspec.template
          if [[ "${{ matrix.parsers.install_info.requires_generate_from_grammar }}" == "true" ]]; 
          then
            sed -i 's/generate_from_grammar\s=\sfalse/generate_from_grammar = true/g' rockspec.template
          fi
          if [[ "${{ matrix.parsers.install_info.generate_requires_npm }}" == "true" ]]; 
          then
            sed -i 's/generate_requires_npm\s=\sfalse/generate_requires_npm = true/g' rockspec.template
          fi
          if [[ -n "${{ matrix.parsers.install_info.location }}" ]]; 
          then
            sed -i 's/location\s=\snil/location = "${{ matrix.parsers.install_info.location }}"/g' rockspec.template
          fi
          cat rockspec.template

      - name: Publish LuaRock (TODO)
        uses: nvim-neorocks/luarocks-tag-release@v5
        if: ${{ env.PUBLISHED_COUNT == '0' }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
          LUAROCKS_TAG_RELEASE_DISABLE_UPLOAD: true
        with:
          name: ${{ env.PARSER_NAME }}
          version: ${{ env.RELEASE_VERSION }}
          summary: tree-sitter parser for ${{ matrix.parser.lang }}
          license: MIT # TODO
          labels: |
            neovim
            tree-sitter
          extra_luarocks_args: |
            --namespace=neorocks


