name: Publish Dev Release LuaRocks

on:
  push:
    branches:
      - 'main'
  schedule:
    # Runs every minute of every 4th hour
    - cron: "30 */12 * * *"
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "MATRIX=$(cat ./plugins.json | tr -d '\n\r')" >> $GITHUB_OUTPUT
  publish:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout plugin repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.plugins.name }}
          path: .

      - run: |
          echo "GITHUB_REPOSITORY_OVERRIDE=${{ matrix.plugins.name }}" >> $GITHUB_ENV
          echo "GITHUB_SHA_OVERRIDE=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Publish Development LuaRock
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: ${{ matrix.plugins.shorthand }}
          dependencies: ${{ matrix.plugins.dependencies }}
          version: "scm"
          summary: ${{ matrix.plugins.summary }}
          license: ${{ matrix.plugins.license }}
          labels: neovim
          test_interpreters: "" # Don't try to run busted tests
          extra_luarocks_args: |
            --namespace=neorocks
            --force
