name: Publish LuaRocks

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define plugins and their dependencies
        plugins:
          - name: "NeogitOrg/neogit"
            shorthand: "neogit" # TODO: Get rid of this somehow
            dependencies: |
              plenary.nvim
            summary: An interactive and powerful Git interface for Neovim, inspired by Magit
            license: MIT

    steps:
      - name: Checkout plugin repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.plugins.name }}
          path: .

      - name: Print plugin directories and environment
        run: |
          ls -a
          printenv

      - name: Get latest tag or commit message
        id: get-release
        run: |
          # Check for tags
          TAG=$(git describe --tags --abbrev=0 || true)

          if [[ -z "$TAG" ]]; then
            # If there is no tag (aka semver versioning)
            # then count the number of commits instead.
            COUNT=$(git rev-list --count HEAD)
            echo "RELEASE_VERSION=0.0.${COUNT}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
          fi

          echo "NEW_COMMIT_COUNT=$(git rev-list --count HEAD --since '4 hours ago')" >> $GITHUB_ENV
          echo "PUBLISHED_COUNT=$(luarocks --server=https://luarocks.org/m/neovim search ${{ matrix.plugins.shorthand }} --porcelain | wc -l)" >> $GITHUB_ENV

      - name: Publish LuaRock
        uses: nvim-neorocks/luarocks-tag-release@target-server-input
        if: ${{ env.NEW_COMMIT_COUNT > 0 || env.PUBLISHED_COUNT == 0 }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: ${{ matrix.plugins.shorthand }}
          dependencies: ${{ matrix.plugins.dependencies }}
          version: ${{ env.RELEASE_VERSION }}
          summary: ${{ matrix.plugins.summary }}
          license: ${{ matrix.plugins.license }}
          labels: neovim
          test_interpreters: "" # Don't try to run busted tests
          target_server: https://luarocks.org/m/neovim
